---
title: "statAnalysis"
output: html_document
date: "2025-03-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Data Cleaning and Missing Values 
education <- read.csv("data/education_career_success.csv")
View(education)
nrow(education)

# Identify any missing data
colSums(is.na(education))
  # Output shows there is no missing data! 

# Check to see what columns are numerical
str(education)

# Create a copy of the dataset to have both the original and normalized data
og_education <- education 

# Define the normalize function
normalize <- function(x) {
  return((x - min(x, na.rm = TRUE)) / (max(x, na.rm = TRUE) - min(x, na.rm = TRUE)))
}

# Select the columns that are numerical to normalize
numeric_columns <- sapply(education, is.numeric)
education[, numeric_columns] <- lapply(education[, numeric_columns], normalize)

# View the original dataset
View(og_education)
# View the normalized data
View(education)

# Remove duplicate data
education <- education[!duplicated(education), ]

# Remove outliers
remove_outliers <- function(x) {
  Q1 <- quantile(x, 0.25, na.rm = TRUE)
  Q3 <- quantile(x, 0.75, na.rm = TRUE)
  IQR <- Q3 - Q1
  lower_limit <- Q1 - 1.5 * IQR
  upper_limit <- Q3 + 1.5 * IQR
  x[x < lower_limit | x > upper_limit] <- NA  # Replace outliers with NA
  return(x)
}

# Apply the function to numeric columns
education[numeric_columns] <- lapply(education[numeric_columns], remove_outliers)


# Save the cleaned dataset
write.csv(education, "data/Cleaned_Education_Data.csv", row.names = FALSE)
```


```{r}
library(ggplot2)

ecs <-read.csv("data/Cleaned_Education_Data.csv")

get_mode <- function(x) {
  ux <- unique(x)
  m <- ux[which.max(tabulate(match(x, ux)))]
  print(toString(m))
}

analyze_column <- function(column,largeDat,name) {
  
  if(largeDat == FALSE){
    cat("Data:\n")
    print(table(column))
  } else {
    options(scipen = 999)
    cat("Data:\n")
    hist(column, main = paste("Histogram of",name), xlab= name)
  }
  
  cat("\nSummary:\n")
  print(summary(column))
  
  cat("\nMode:\n")
  get_mode(column)
  
  cat("\n--------------------------\n")
}

print3 <- function(data, columns = NULL,large) {
  for (col in columns) {
    if (col %in% names(data)) {
      cat("Column:", col, "\n")
      analyze_column(data[[col]], largeDat = large, name=col)
    } else {
      cat("Column", col, "column missing.\n")
    }
  }
}
```

```{r}
print3(ecs, columns = c("High_School_GPA","SAT_Score","University_Ranking","University_GPA","Starting_Salary"), large=TRUE)
```

```{r}
print3(ecs, columns = c("Age","Internships_Completed","Projects_Completed","Certifications","Soft_Skills_Score","Networking_Score","Job_Offers","Career_Satisfaction","Years_to_Promotion","Work_Life_Balance"), large=FALSE)
```

```{r}
ageTab <- table(ecs$Gender)
ageTab
pie(ageTab, main ="Gender")
```

```{r}
stuTab <- table(ecs$Field_of_Study)
stuTab
pie(stuTab, main ="Field of Study")
```

```{r}
jobLvlTab <- table(ecs$Current_Job_Level)
jobLvlTab
pie(jobLvlTab, main ="Current Job Level")
```

```{r}
entTab <- table(ecs$Entrepreneurship)
entTab
pie(entTab, main ="Entrepreneurship")
```

```{r}
```